### ISSUE TITLE
PS/Worker definitions in api/* should be pointer

### ISSUE THREAD

**Issue by shinytang6** [PaddleFlow/paddle-operator#51]
According to the k8s api conventions:
```
Optional fields have the following properties:

They have the +optional comment tag in Go.
They are a pointer type in the Go definition (e.g. AwesomeFlag *SomeFlag) or have a built-in nil value (e.g. maps and slices).
The API server should allow POSTing and PUTing a resource with this field unset.
```

problem we met:
currently `PS` and `Worker` is non-pointer, when we `json.Marshal` a `PaddleJob` without ps def,  will appear something like that which make submission err because of `"containers":null`
```
"spec":{"ps":{"template":{"metadata":{"creationTimestamp":null},"spec":{"containers":null}}}
```

So IMO, api def should be improved according to the conventions.

ref:
1. https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#optional-vs-required

**Comment by kuizhiqing** [comment]
good point, we will fix it soon.

**Comment by kuizhiqing** [comment]
fixed by https://github.com/PaddleFlow/paddle-operator/pull/52
