### ISSUE TITLE
Fully integrate with volcano

### ISSUE THREAD

**Issue by shinytang6** [PaddleFlow/paddle-operator#59]
The current integration with volcano is actually very weak, the podgroup need to be created manually and does not have fully batch-scheduling capabilities.

The missing functions are as follows:
* automatically create podgroup
* delay pods creation according to the status of podgroup

**Comment by shinytang6** [comment]
> The current integration with volcano is actually very weak, the podgroup need to be created manually and does not have fully batch-scheduling capabilities.
> 
> The missing functions are as follows:
> 
> 1. automatically create podgroup
> 2. delay pods creation according to the status of podgroup

**Comment by kuizhiqing** [comment]
According to volcano's strategy, pg will be created automatically if 

*schedulerName: volcano*

 is detected in the spec, therefore, batch-scheduling is enabled in this case.

Indeed, the weakness of the integration address when more features like queue/priority are needed which can be achieve by creating pg manually. More generic support for this is under consideration.

**Comment by shinytang6** [comment]
> According to volcano's strategy, pg will be created automatically if
> 
> _schedulerName: volcano_
> 
> is detected in the spec, therefore, batch-scheduling is enabled in this case.
> 
> Indeed, the weakness of the integration address when more features like queue/priority are needed which can be achieve by creating pg manually. More generic support for this is under consideration.

According to the implementation of other job operators, a field such like enableGangSchedule is added to indicate whether pg needs to be created automatically.

If you create a pg manually, you need to fill in some necessary fields such like `minResources`, `minMember`, they should be bound to the job (automatically created),  leaving it to user is not so reasonable.

**Comment by kuizhiqing** [comment]
As I mentioned in https://github.com/volcano-sh/volcano/issues/1589, the implementation of tf-operator may not beautiful enough, but it is more practical and user friendly indeed.

Well, may be we should add some *invasive* code for volcano and we can put it on the agenda now.

**Comment by shinytang6** [comment]
> As I mentioned in [volcano-sh/volcano#1589](https://github.com/volcano-sh/volcano/issues/1589), the implementation of tf-operator may not beautiful enough, but it is more practical and user friendly indeed.
> 
> Well, may be we should add some _invasive_ code for volcano and we can put it on the agenda now.

Great, l can help with that.

**Comment by shinytang6** [comment]
https://github.com/PaddleFlow/paddle-operator/pull/60 is merged.
/close
